Lesson 4 Step 1
MZaimanov/TestGuru pull request #3
Opened 2018-04-24 07:41 UTC by MZaimanov

2018-04-24 17:54 UTC, psylone requested changes

2018-04-24 17:54 UTC, psylone commented on .byebug_history
> +user.with_options
Это лучше удалить из репозитория.

2018-04-24 17:54 UTC, psylone commented on app/models/user.rb
> +    test.where(level: level)
Это не будет работать, метод `test` не определён для объекта пользователя.

2018-04-24 17:54 UTC, psylone commented on app/models/test.rb
> +    by_category(title).pluck(:title)
Метод `by_category` не определён для класса `Test`.

2018-04-25 16:57 UTC, iBublik commented on app/models/test.rb
> +    Test.joins('
`Test` можно опустить, т.к. в контексте этого метода `self == Test`

2018-04-25 16:57 UTC, iBublik commented on app/models/test.rb
> +      .where('categories.title = :category', category: category)
Используй хеш для условий поиска - `where(categories: { title: category })`. Хеши намного удобнее изменять

2018-04-25 16:57 UTC, iBublik commented on app/models/user.rb
> +      .where('users_tests.user_id = :user_id AND level = :level',
Тут так же лучше использовать хеш

2018-04-25 16:57 UTC, iBublik commented on db/seeds.rb
> +users = User.create([
Лучше использовать бэнг-версию метода - `create!`. Она бросит исключение, если какая-то запись не создалась. Позволит избежать неправильного заполнения базы

2018-04-25 16:57 UTC, iBublik commented on db/seeds.rb
> +INSERT INTO users_tests(user_id, test_id) VALUES
Для этой таблицы стоит создать модель. Она нам еще понадобится

2018-04-27 09:56 UTC, merged